### ISSUE TITLE
Error parsing a password with special characters

### ISSUE THREAD

**Issue by alpegon** [grycap/ec3#2]
In the auth file I used a password with the single quote ( ' ) character in it.
In the line 648 of the ec3 file there is a call to a radl parser: radl = parse_radl(info)
When this parser reads the password thinks that the single quote of the password is the end of the auth file, tries to execute the rest of the code (in this case the remaining password) and fails.

**Comment by micafer** [comment]
The problem is related with the IM service it will be solved in the next release of the IM.
