### ISSUE TITLE
NTP

### ISSUE THREAD

**Issue by iblanque** [grycap/ec3#25]
Hola,

He visto que en la instalación de mesos desde ec3 no se instala el ntp. Tampoco lo he encontrado como un módulo separado.

Imagino que sería conveniente ponerlo por defecto, o al menos dar la opción para ello.

Gracias

**Comment by amcaar** [comment]
Hola,

¿la instalación de mesos la llevas a cabo usando el rol "ansible-role-mesos"? Porque si es así, debería instalar NTP ya que es una dependencia del propio rol de mesos (y del resto de LRMS que soporta EC3). Aun así, podríamos añadir una receta a EC3 que instale el rol de "ansible-role-ntp" si es necesario.

Saludos,
Amanda.

**Comment by alpegon** [comment]
Como dice Amanda el rol de ntp es una dependencia directa del rol de mesos.
Este problema ha sido debido a unos comandos que puse para saltarse la instalación si ntp ya está instalado.
Como lo detecta en el front no lo instala en los nodos.
He quitado esas líneas del rol de ansible, ya debería volver a fucionar.

**Comment by iblanque** [comment]
Correcto, no lo había comprobado en esta versión con roles.
