### ISSUE TITLE
Provide the capability of reconfiguring an active cluster with additional recipes

### ISSUE THREAD

**Issue by iblanque** [grycap/ec3#30]
Sometimes I have a fully working cluster which I would like to extend with additional software packages. Or simply, I would like to work incrementally to identify issues.

It may be interesting to have a "reconfigure" command that installs a template module in the existing nodes, and (much more interesting, since this is easy to do already with IM), registers this changes in the template RADL used in CLUES for new nodes.

Thanks!

**Comment by amcaar** [comment]
In fact, the "ec3 reconfigure" command allows that bejhaviour with the option "--add", to add a piece of RADL" and the option "-r, --reload", to reload templates used to launch the cluster and reconfigure the cluster with them (useful if templates changed). Try that options and if you still have problems, we look at them.
