### ISSUE TITLE
IM on front-end node unable to create worker nodes using OCCI

### ISSUE THREAD

**Issue by alahiff** [grycap/ec3#44]
Firstly, I should say I'm not sure whether I should submit this issue to grycap/ec3, grycap/ansible-role-im or grycap/im, so I apologise if I  made the wrong choice. I encountered the problem while testing EC3.

I've tried using the example templates for deploying a SLURM cluster, in my case on EGI FedCloud using the EGI CentOS 7 image. EC3 is using a local IM (running in a Docker container). The front-end node can be deployed successfully, however there are problems when the IM on the front-end node tries to create worker nodes:
```
Error querying the OCCI server: HTTPSConnectionPool(host='carach5.ics.muni.cz', port=11443): Max retries exceeded with url: /-/ (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'tlsv1 alert unknown ca')],)",),))
```
I assume this is due to the versions of python-requests/openssl etc installed on the front-end but I'm not exactly sure how to fix the problem. So far I've only found a slightly drastic workaround - I removed the grycap.im role from the frontend and added config to install Docker and run IM on the front-end using the indigodatacloud/im Docker image, as the IM Docker container doesn't have this problem.

Note that deploying a cluster using http://servproject.i3m.upv.es/ec3/ gives the same error when IM tries to create a worker node.

**Comment by micafer** [comment]
Hi @alahiff,
I have tried using EC3 portal and I do not get this error.
It worked properly.
Could you try again?

**Comment by alahiff** [comment]
Hi @micafer, I just tried again and got the same error. I did this:

1. Clicked on the EGI FedCloud box on the web page
2. Selected fedcloud.egi.eu as the VO
3. Selected CESNET-MetaCloud as the Endpoint, also provided my proxy
4. Skipped the MyProxy details page
5. Selected EGI CentOS 7 as the operating system
6. Selected “2048 MB - 2 CPUs” for both the front-end instance type and worker node instance type
7. Selected SLURM as the LRMS
8. Skipped the Software Packages page
9. Set the max size of the cluster as 5 nodes

Once the front-end node had finished installing I submitted a basic hello world job using sbatch. Looking in /var/log/clues2/clues2.log were errors like:

```
Attempt 3: Error launching the VMs of type wn1 to cloud ID occi of type OCCI. Cloud Provider Error: Error querying the OCCI server: HTTPSConnectionPool(host='carach5.ics.muni.cz', port=11443): Max retries exceeded with url: /-/ (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'tlsv1 alert unknown ca')],)",),))
```

**Comment by micafer** [comment]
Hi @alahiff,
I finally get the problem. It was a problem with the python-requests package in the grycap.im ansible role.
Not it should work.
Can you test it?

**Comment by alahiff** [comment]
Hi @micafer,
I can confirm it works now. Thanks!
