### ISSUE TITLE
Templates dockers-compose and jupyter 

### ISSUE THREAD

**Issue by gmolto** [grycap/ec3#51]
Using a fresh pull from EC3 (im-rest branch) and attempting to issue:
```
ec3 templates
```
throws the error:
```
Error processing 'docker-compose': Line 1: Parse error in: LexToken(VAR,'compose',1,19)
```
If you remove the template docker-compose.radl the error is:
```
Error processing 'jupyter': Line 1: Parse error in: LexToken(VAR,'notebook',1,20)
```
If you remove jupyter.radl then everything works as expected.

**Comment by amcaar** [comment]
Thank you for reporting this. I'll investigate if the problem remians in the name of the recipe, because of the "-" character.

**Comment by amcaar** [comment]
I deleted the "-" characters in both recipes. Try to test it again to see if it solves the problem.

**Comment by gmolto** [comment]
It works now. Thanks. Closing the issue.
