### ISSUE TITLE
Unable to find template in ~/.ec3/templates

### ISSUE THREAD

**Issue by gmolto** [grycap/ec3#52]
EC3 is meant to look for the templates in: ['./templates', '~/.ec3/templates', '/etc/ec3/templates']

I have checked that (at least in macOS) the folders './templates' and '/etc/ec3/templates'  are searched for but not the templates in  '~/.ec3/templates'

**Comment by amcaar** [comment]
Thank you for this, it was true that EC3 ignored the  '~/.ec3/templates' directory. Now it should be fixed. We will merge this commit to 'master' branch soon.
