### ISSUE TITLE
Error with python3

### ISSUE THREAD

**Issue by alpegon** [grycap/ec3#55]
When I try to run the command:

`./ec3 launch oscar ubuntu16 kubernetes_oscar_latest -a auth.dat -u $IM_ENDPOINT`

 using python3.6 I get the following error:

`Error launching front-end: cannot represent an object: <map object at 0x7f94ed797a90>`

With python2.7 there is no problem.
I'm using `Python 3.6.6` in `Ubuntu 18.04`

**Comment by micafer** [comment]
Hi @alpegon,
Colud you try to test the devel branch?

**Comment by alpegon** [comment]
The error has changed. The new error is:
`Error while configuring the infrastructure: 'map' object is not subscriptable`

This only happens when launching an infrastructure, the rest of the commands seem to work fine

**Comment by alpegon** [comment]
New error !
This happend when I executed `./ec3 list` after the infrastructure deployment failed.

```
 Traceback (most recent call last):
  File "./ec3", line 1759, in <module>
    CLI.run(commands)
  File "./ec3", line 604, in run
    CLI.options.func(CLI.options)
  File "./ec3", line 973, in run
    output = dump_json(info) if options.json else dump_table(info, ["name", "state", "IP", "nodes"])
  File "./ec3", line 114, in dump_table
    for d in l ])
  File "./ec3", line 114, in <listcomp>
    for d in l ])
  File "./ec3", line 113, in <listcomp>
    o.extend([ "".join([ "{0: {a}{width}}".format(d[f], a=align.get(f, "^"), width=widths[f]) for f in order ])
TypeError: unsupported format string passed to NoneType.__format__
```

I have this error with python2 and python3. It looks like one of the fields of the infrastructure is not correctly filled and the parser explodes.

**Comment by micafer** [comment]
Hi @alpegon,
I think I get it. I tested it in the same environment and it worked.
Could you test it again?

**Comment by alpegon** [comment]
Devel branch is working now with python3.

Thanks !
