### ISSUE TITLE
Error destroying clusters

### ISSUE THREAD

**Issue by srisco** [grycap/ec3#62]
Hi, today I updated ec3 (master branch 4fadb51f4d05583104e80f04e83c39e4eeff31cd) and, after creating a cluster with no problems, I've got this error message when I tried to delete it:

```
$ python2 ./ec3 destroy mycluster                                 
WARNING: you are going to delete the infrastructure (including frontend and nodes).
Continue [y/N]? y
Error destroying cluster 'mycluster': name 'y' is not defined
```

Using `Python 2.7.15` on Arch Linux.

**Comment by gmolto** [comment]
I hit exactly the same issue.

In the meantime, you can workaround this by using the ```--force``` flag.

```sh
ec3 destroy --force cluster-name
WARNING: you are going to delete the infrastructure (including frontend and nodes).
Continue [y/N]? y
Error destroying cluster 'oscar-test-aws-1': name 'y' is not defined
```

**Comment by srisco** [comment]
@gmolto using the `-y` flag the cluster should be deleted without any problem.

Anyways, I pushed #63 to fix it.
