### ISSUE TITLE
Error building docker image from "docker" directory.

### ISSUE THREAD

**Issue by kmlTE** [grycap/ec3#80]
Hi,

there is an error while building ec3 docker image from the "docker" directory. It appears that the requests package depends on pyrsistent package, which now requires python3.

docker build -t grycap/ec3:latest .
Sending build context to Docker daemon  2.048kB
Step 1/6 : FROM alpine:3.8
3.8: Pulling from library/alpine
486039affc0a: Pull complete 
Digest: sha256:2bb501e6173d9d006e56de5bce2720eb06396803300fe1687b58a7ff32bf4c14
Status: Downloaded newer image for alpine:3.8
 ---> c8bccc0af957
Step 2/6 : LABEL maintainer="Germán Moltó <gmolto@dsic.upv.es>"
 ---> Running in e360906a42e5
Removing intermediate container e360906a42e5
 ---> 53efbc6c4393
Step 3/6 : LABEL version="2.0"
 ---> Running in b52dc0ddbcba
Removing intermediate container b52dc0ddbcba
 ---> 519015180b1a
Step 4/6 : LABEL description="Elastic Cloud Computing Cluster (EC3) - http://www.grycap.upv.es/ec3"
 ---> Running in ca803648bdf0
Removing intermediate container ca803648bdf0
 ---> 1cc61967395d
Step 5/6 : RUN apk add --no-cache py-pip python sshpass openssh-client &&      pip --no-cache-dir install ec3-cli &&      apk del py-pip
 ---> Running in f4c0e604b04b
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
(1/15) Installing openssh-keygen (7.7_p1-r4)
(2/15) Installing openssh-client (7.7_p1-r4)
(3/15) Installing libbz2 (1.0.6-r7)
(4/15) Installing expat (2.2.8-r0)
(5/15) Installing libffi (3.2.1-r4)
(6/15) Installing gdbm (1.13-r1)
(7/15) Installing ncurses-terminfo-base (6.1_p20180818-r1)
(8/15) Installing ncurses-terminfo (6.1_p20180818-r1)
(9/15) Installing ncurses-libs (6.1_p20180818-r1)
(10/15) Installing readline (7.0.003-r0)
(11/15) Installing sqlite-libs (3.25.3-r4)
(12/15) Installing python2 (2.7.15-r3)
(13/15) Installing py-setuptools (39.1.0-r0)
(14/15) Installing py2-pip (10.0.1-r0)
(15/15) Installing sshpass (1.06-r0)
Executing busybox-1.28.4-r3.trigger
OK: 66 MiB in 28 packages
Collecting ec3-cli
  Downloading https://files.pythonhosted.org/packages/0a/a6/0069fcd2c167c7932928ae13cc8d648b1ccb725a3588e456ccf474b2605c/ec3-cli-2.0.1.tar.gz (64kB)
Collecting ply (from ec3-cli)
  Downloading https://files.pythonhosted.org/packages/a3/58/35da89ee790598a0700ea49b2a66594140f44dec458c07e8e3d4979137fc/ply-3.11-py2.py3-none-any.whl (49kB)
Collecting PyYAML (from ec3-cli)
  Downloading https://files.pythonhosted.org/packages/64/c2/b80047c7ac2478f9501676c988a5411ed5572f35d1beff9cae07d321512c/PyYAML-5.3.1.tar.gz (269kB)
Collecting jsonschema (from ec3-cli)
  Downloading https://files.pythonhosted.org/packages/c5/8f/51e89ce52a085483359217bc72cdbf6e75ee595d5b1d4b5ade40c7e018b8/jsonschema-3.2.0-py2.py3-none-any.whl (56kB)
Collecting requests (from ec3-cli)
  Downloading https://files.pythonhosted.org/packages/45/1e/0c169c6a5381e241ba7404532c16a21d86ab872c9bed8bdcd4c423954103/requests-2.24.0-py2.py3-none-any.whl (61kB)
Requirement already satisfied: setuptools in /usr/lib/python2.7/site-packages (from jsonschema->ec3-cli) (39.1.0.post20180508)
Collecting importlib-metadata; python_version < "3.8" (from jsonschema->ec3-cli)
  Downloading https://files.pythonhosted.org/packages/8e/58/cdea07eb51fc2b906db0968a94700866fc46249bdc75cac23f9d13168929/importlib_metadata-1.7.0-py2.py3-none-any.whl
Collecting pyrsistent>=0.14.0 (from jsonschema->ec3-cli)
  Downloading https://files.pythonhosted.org/packages/7d/ae/90ddcf28fb8eee5d4990920586d2856342e42faa95f39223f0b9762ef264/pyrsistent-0.17.2.tar.gz (106kB)
pyrsistent requires Python '>=3.5' but the running Python is 2.7.15
You are using pip version 10.0.1, however version 20.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c apk add --no-cache py-pip python sshpass openssh-client &&      pip --no-cache-dir install ec3-cli &&      apk del py-pip' returned a non-zero code: 1

A workaround can be to install specific version of pyrsistent before installing ec3-cli in Dockerfile:
```
RUN apk add --no-cache py-pip python sshpass openssh-client && \
     pip --no-cache-dir install pyrsistent==0.16.0 ec3-cli && \
     apk del py-pip
```

**Comment by micafer** [comment]
thanks @kmlTE, we fixed it in PR #81, moving it to python3.
